### ISSUE TITLE
Publish docs site on github pages

### ISSUE THREAD

**Issue by lindskogen** [mulias/roc-array2d#1]
Hi, I found your library to be very useful but I had to pull down the source and generate and host the docs manually. 

I think it could be more usable to publish the generated docs as a static site on github pages :)

**Comment by mulias** [comment]
Thanks for the feedback! I'll definitely be setting that up, maybe some time next month. In the meantime I'll keep this open as a reminder.

**Comment by lindskogen** [comment]
Luke has this workflow setup which you should be able to steal straight up 😃  https://github.com/lukewilliamboswell/roc-json/blob/main/.github/workflows/generate-docs.yaml

**Comment by mulias** [comment]
Docs are now deployed to https://mulias.github.io/roc-array2d/
